### ISSUE TITLE
Unsupported 'dets' input type '<class 'ultralytics.engine.results.Boxes'>', valid format is np.ndarray

### ISSUE THREAD

**Issue by BigHuu** [mikel-brostrom/yolo_tracking#1071]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Error occurred when calling the ‘update’ function in /boxmot/utils/__init__.py: "mc_dets = self.update(instance, dets, im)':

Unsupported 'dets' input type '<class 'ultralytics.engine.results.Boxes'>', valid format is np.ndarray

### Environment

-Yolo Tracking10.0.33  python3.10.9  torch2.0.0+cu117
pip check:
super-gradients 3.1.3 has requirement numpy<=1.23, but you have numpy 1.23.1.
Other environments are normal.

### Minimal Reproducible Example

When I Execute the examples/track.py, the error occurs:Unsupported 'dets' input type '<class 'ultralytics.engine.results.Boxes'>', valid format is np.ndarray.
Some params in track.py:
def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--yolo-model', type=Path, default=WEIGHTS / 'yolov8n',
                        help='yolo model path')
    parser.add_argument('--reid-model', type=Path, default=WEIGHTS / 'resnet50_msmt17_256x128.torchscript',
                        help='reid model path')
    parser.add_argument('--tracking-method', type=str, default='deepocsort',
                        help='deepocsort, botsort, strongsort, ocsort, bytetrack')
    parser.add_argument('--source', type=str, default=WEIGHTS / 'sample.mp4',
                        help='file/dir/URL/glob, 0 for webcam')

"Please help me, I am extremely grateful."

**Comment by mhanis27** [comment]
I'm also encountering the same issue. Thanks for bringing this up 👍.

**Comment by mikel-brostrom** [comment]
Give me the exact command. I cannot help you otherwise

**Comment by BigHuu** [comment]
-boxmot10.0.32
-Yolo Tracking10.0.33 
-python3.10.9 
-torch2.0.0+cu117

(1)I downloaded the zip file for YOLO tracking from this link (https://github.com/mikel-brostrom/yolo_tracking), then I extracted it and opened it with PyCharm. 
(2)After that, I ran "pip install -r requirements.txt" in this environment. 
(3)After specifying the model path, I ran the track.py file located in the ‘examples’ directory, and encountered the above-mentioned error. While debugging, I observed that "dets" has the following structure: dets={Boxes:(8,6)}, including "boxes={ndarray:(8,6)}", "cls={ndarray:(8,)}", "conf={ndarray:(8,)}", etc.

pip check:
super-gradients 3.1.3 has requirement numpy<=1.23, but you have numpy 1.23.1.(The requirements.txt requires numpy 1.23.1)

I suspect that there might be an issue with the environment or version conflicts. I kindly request your assistance in examining the situation. I am very grateful for your answer.

**Comment by BigHuu** [comment]
> I'm also encountering the same issue. Thanks for bringing this up 👍.
> 
> Here's what I got:
> 
> ```
> 2023-08-11 12:34:53.362 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "examples\weights\osnet_x0_25_msmt17.pt"
> 2023-08-11 12:34:53.362 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
> 
>  File "boxmot\trackers\deepocsort\deep_ocsort.py", line 361, in update
>     assert isinstance(dets, np.ndarray), f"Unsupported 'dets' input type '{type(dets)}', valid format is np.ndarray"
> AssertionError: Unsupported 'dets' input type '<class 'ultralytics.engine.results.Boxes'>', valid format is np.ndarray
> ```

"May I know if you have found a solution?"

**Comment by Alhambra-H** [comment]
i run into the same problem, i just input the video path :E:\zxsl\VCG42N1452360222.mp4, i have downloaded the yolov8n.pt and osnet_x0_25_msmt17.pt already. and the boxmot version should be 10.0.34,(cus i downloaded the code minutes ago)

**Comment by Alhambra-H** [comment]
`2023-08-11 16:58:34.581 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "E:\zxsl\tracking\yolo_tracking-master\examples\weights\osnet_x0_25_msmt17.pt"
2023-08-11 16:58:34.581 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')

video 1/1 (1/392) E:\zxsl\VCG42N1452360222.mp4: 384x640 (no detections), 73.0ms
Traceback (most recent call last):
  
File "E:/zxsl/tracking/yolo_tracking-master/examples/track.py", line 194, in <module>
    run(opt)``
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
 
 File "E:/zxsl/tracking/yolo_tracking-master/examples/track.py", line 100, in run
    for frame_idx, r in enumerate(results):
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\ultralytics\engine\predictor.py", line 258, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\ultralytics\engine\predictor.py", line 353, in run_callbacks
    callback(self)
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\ultralytics\trackers\track.py", line 48, in on_predict_postprocess_end
    tracks = predictor.trackers[i].update(det, im0s[i])
  
File "E:\zxsl\tracking\yolo_tracking-master\boxmot\utils\__init__.py", line 57, in wrapper
    mc_dets = self.update(instance, dets, im)
 
 File "E:\zxsl\tracking\yolo_tracking-master\boxmot\trackers\deepocsort\deep_ocsort.py", line 361, in update
      assert isinstance(dets, np.ndarray), f"Unsupported 'dets' input type '{type(dets)}', valid format is np.ndarray"

AssertionError: Unsupported 'dets' input type '<class 'ultralytics.engine.results.Boxes'>', valid format is np.ndarray`

**Comment by Alhambra-H** [comment]
`2023-08-11 16:58:34.581 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "E:\zxsl\tracking\yolo_tracking-master\examples\weights\osnet_x0_25_msmt17.pt"
2023-08-11 16:58:34.581 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
video 1/1 (1/392) E:\zxsl\VCG42N1452360222.mp4: 384x640 (no detections), 73.0ms

Traceback (most recent call last):
  
File "E:/zxsl/tracking/yolo_tracking-master/examples/track.py", line 194, in <module>
    run(opt)
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  
File "E:/zxsl/tracking/yolo_tracking-master/examples/track.py", line 100, in run
    for frame_idx, r in enumerate(results):
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\ultralytics\engine\predictor.py", line 258, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\ultralytics\engine\predictor.py", line 353, in run_callbacks
    callback(self)
  
File "E:\Anaconda\envs\yolov8\lib\site-packages\ultralytics\trackers\track.py", line 48, in on_predict_postprocess_end
    tracks = predictor.trackers[i].update(det, im0s[i])
  
File "E:\zxsl\tracking\yolo_tracking-master\boxmot\utils\__init__.py", line 57, in wrapper
    mc_dets = self.update(instance, dets, im)
  
File "E:\zxsl\tracking\yolo_tracking-master\boxmot\trackers\deepocsort\deep_ocsort.py", line 361, in update
    assert isinstance(dets, np.ndarray), f"Unsupported 'dets' input type '{type(dets)}', valid format is np.ndarray"

AssertionError: Unsupported 'dets' input type '<class 'ultralytics.engine.results.Boxes'>', valid format is np.ndarray`

**Comment by mikel-brostrom** [comment]
Reclone and start from a clean slate. I cannot reproduce this.  This error:

`Unsupported 'dets' input type '<class 'ultralytics.engine.results.Boxes'>', valid format is np.ndarray`

Is triggered after checking the inputs to the trackers. What is passed to the trackers is ALWAYS:

`det = predictor.results[i].boxes.cpu().numpy()`

which is a numpy array. This probably arrise due to an old version of this repo together with a mismatching ultralytics pkg installation. Again, just start from a clean slate.

**Comment by Yingrjimsch** [comment]
Ok I've fixed the problem for me. What I've done is adding to every `update` function the line `dets = dets.data` at the top. In my opinion that's an error of yolov8 `boxes.cpu().numpy()` does not return a nparray anymore since boxes.boxes is deprecated.

I hope that helped anyone. 
@mikel-brostrom I'm not sure if you want to fix it in your code or open an issue with yolov8 but let me know if I should create a pull request.

**Comment by StormS0** [comment]
> Ok I've fixed the problem for me. What I've done is adding to every `update` function the line `dets = dets.data` at the top. In my opinion that's an error of yolov8 `boxes.cpu().numpy()` does not return a nparray anymore since boxes.boxes is deprecated.
> 
> I hope that helped anyone. @mikel-brostrom I'm not sure if you want to fix it in your code or open an issue with yolov8 but let me know if I should create a pull request.
Can you submit the following example? I have also encountered this issue. Thank you

**Comment by mikel-brostrom** [comment]
But is tracking working on the ultralytics pkg? DId anybody tried?

**Comment by StormS0** [comment]
> 但是 Ultralytics pkg 上的追踪功能有效吗？有人试过吗？

Ultralytics 8.0.157 G:\yolo_tracking-10.0.37\venv\Lib\site-packages\ultralytics\trackers\track.py 
def on_predict_postprocess_end(predictor):
    """Postprocess detected boxes and update with object tracking."""
    bs = predictor.dataset.bs
    im0s = predictor.batch[1]
    for i in range(bs):
        det = predictor.results[i].boxes.cpu().numpy()
        if len(det) == 0:
            continue
        tracks = predictor.trackers[i].update(det, im0s[i])
        if len(tracks) == 0:
            continue
        idx = tracks[:, -1].astype(int)
        predictor.results[i] = predictor.results[i][idx]
        predictor.results[i].update(boxes=torch.as_tensor(tracks[:, :-1]))
        
Maybe det = predictor.results[i].boxes.cpu().numpy()  not work .  This leads to incorrect input results.
example ocsort
G:\yolo_tracking-10.0.37\examples\boxmot\trackers\ocsort\ocsort.py   line217   
def update(self, dets, _):   
    dets = dets.data


add   { dets = dets.data}  This can work normally

**Comment by mikel-brostrom** [comment]
Yup, that may work @StormS0. But the idea here is to make tracker independent from the object detector used. So adding `dets = dets.data` is not an option. Locally, for you it is okay

**Comment by StormS0** [comment]
> 是的，这可能有效.但这里的想法是使跟踪器独立于所使用的对象检测器。因此，添加不是一种选择。在当地，对你来说没关系`dets = dets.data`

I guess this may be a bug in the Ultralytics version update, because predictor. results [i]. boxes have been deprecated?

**Comment by mikel-brostrom** [comment]
What is the new standard @StormS0? If this is deprecated in Ultralytics and has not been updated, an issue should be created in that repo.

**Comment by mikel-brostrom** [comment]
Ahaa yes, I see. 

`results[i].boxes.data` should be used

**Comment by StormS0** [comment]
> Ahaa yes, I see.
> 
> `results[i].boxes.data` should be used

yes,i find this code G:\yolov82\10.0.15\examples\dist\track2\ultralytics\yolo\engine\results.py   line 431  

`
@property
    def boxes(self):
        """Return the raw bboxes tensor (deprecated)."""
        LOGGER.warning("WARNING ⚠️ 'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.")
        return self.data
`

**Comment by mikel-brostrom** [comment]
A temporary fix is to:

`pip install git+https://github.com/mikel-brostrom/ultralytics.git`

**Comment by mikel-brostrom** [comment]
But an issue should be created for this in the Ultralytics repo

**Comment by StormS0** [comment]
> https://github.com/mikel-brostrom/ultralytics.git
tracks = predictor.trackers[i].update(det, im0s[i])
sub update(det, im0s[i])  edit
Perhaps this is a temporary compatibility solution.


    def update(self, dets, img):
        if str(type(dets)) == "<class 'ultralytics.engine.results.Boxes'>":
            dets = dets.data
        assert isinstance(
                    dets, np.ndarray
                ), f"Unsupported 'dets' input format '{type(dets)}', valid format is np.ndarray"

**Comment by mikel-brostrom** [comment]
Alright @StormS0. Make sense as a temporary fix
