### ISSUE TITLE
Bytetrack only activates new tracks if frame_id == 1?

### ISSUE THREAD

**Issue by cristianobac** [mikel-brostrom/yolo_tracking#1170]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello.  I hope someone can help me. 

I am performing some experiments and is occurring that some high confidence detections are not tracked. I've noticed that the Strack activate method used in Bytetrack has the condition below. Note that it is followed by a comment where there is no if condition.

if frame_id == 1:
    self.is_activated = True

\# self.is_activated = True

Is this conditioning correct? 

Thanks.

**Comment by Justin900429** [comment]
The reason is to ensure that the new tracklets will be addressed after old tracklets. However, the first frame has no history information, so the new detections should be activated directly.
(All tracklets can be activated by `update` or `reactivated`.)

The original implementation used the same logic [here](https://github.com/ifzhang/ByteTrack/blob/d1bf0191adff59bc8fcfeaa0b33d3d1642552a99/yolox/tracker/byte_tracker.py#L53-L54).

Hope this help :)

**Comment by cristianobac** [comment]
For sure it helps. Thanks!
