### ISSUE TITLE
3 Questions: 1. AttributeError: 'DeepOCSort' object has no attribute 'reset', 2. yolov5 model support, 3. Applying custom pre-trained yolo model + tracker  

### ISSUE THREAD

**Issue by timingisnow** [mikel-brostrom/yolo_tracking#1300]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, I'm trying to apply various tracker to yolo model(v5, v8, nas..)

### First, basically tried to apply only my video source
python examples/track.py --source /AAA.avi
Error -> **AttributeError: 'DeepOCSort' object has no attribute 'reset'**
How can I solve the above error?

### Second, tried to apply my video + pre-trained yolov5s model
python examples/track.py --yolo-model /weights/best.pt --source /AAA.avi
Error -> 
![image](https://github.com/mikel-brostrom/yolo_tracking/assets/67563871/57f0aff1-2cfa-494d-856f-27a0ec4a1c66)
How can I apply my pre-trained model with optional tracker? 
And I found yolov5 + tracker(https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) but now I can't find it. 

### Third, actually, my goal is to test _**yolo model(pre-trained yolov5, yolov8, yolox, yolo nas) + various optional tracker**_
(pre-trained yolo models were trained with custom dataset)
Is there any easy guide for how to use CLI or python? 

Please let me know the problems and how to solve them.

Thanks,

**Comment by mikel-brostrom** [comment]
> First, basically tried to apply only my video source

https://github.com/mikel-brostrom/yolo_tracking/issues/1263#issuecomment-1898657606

> Second, tried to apply my video + pre-trained yolov5s model

Yolov5 is not official supported in this repo as there is no pip package for it. You could add the Yolov5 repo as a submodule and load the needed resources from there.

> Is there any easy guide for how to use CLI or python?

Under README you will find examples

**Comment by yjseok** [comment]
Thanks Mikel.

As you said in "Custom object detection model tracking example" and Complete version to use yolov5 model,
I added yolov5 repo as a submodule and want to use inference part in detect.py.
To substitute by my yolov5 detector pretrained on custom dataset, in while loop in Complete code,
I don't know how to apply inferencing of detect.py because there's a bit difference that
in Complete code, I have to inference every video frame, on the other hand detect.py of yolov5 inference as batch with for loop. 
Can anybody help poor yolo starter? How can I apply yolov5 detect.py on  "Custom object detection model tracking example - Complete example code"?

**Comment by Elhadji411** [comment]
Hi dear IS it possible to add a function in the track.py fille to plot x1,y1,X2,y2, id ,classe and conf, so WE Can use cv2.rectangle for exemple to customise thé output and also add some logics🙏
![Screenshot_20240308-202732](https://github.com/mikel-brostrom/yolo_tracking/assets/150876571/f0f2b89f-7d3d-45ad-9177-63bd9a63fd2d)
 For exemple this kind of fonction in the track.py file🙏🙏🙏🙏
