### ISSUE TITLE
trackeval.utils.TrackEvalException: Tracker file not found: labels//MOT16-11.txt

### ISSUE THREAD

**Issue by LinaZhangUSC** [mikel-brostrom/yolo_tracking#947]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Evaluation

### Bug

==========================================
SLURM_JOB_ID = 15270262
SLURM_JOB_NODELIST = d14-16
TMPDIR = /tmp/SLURM_15270262
==========================================
no change     /spack/conda/miniconda3/23.3.1/condabin/conda
no change     /spack/conda/miniconda3/23.3.1/bin/conda
no change     /spack/conda/miniconda3/23.3.1/bin/conda-env
no change     /spack/conda/miniconda3/23.3.1/bin/activate
no change     /spack/conda/miniconda3/23.3.1/bin/deactivate
no change     /spack/conda/miniconda3/23.3.1/etc/profile.d/conda.sh
no change     /spack/conda/miniconda3/23.3.1/etc/fish/conf.d/conda.fish
no change     /spack/conda/miniconda3/23.3.1/shell/condabin/Conda.psm1
no change     /spack/conda/miniconda3/23.3.1/shell/condabin/conda-hook.ps1
no change     /spack/conda/miniconda3/23.3.1/lib/python3.10/site-packages/xontrib/conda.xsh
no change     /spack/conda/miniconda3/23.3.1/etc/profile.d/conda.csh
modified      /home1/linazhan/.bashrc

==> For changes to take effect, close and re-open your current shell. <==

Added mamba to /home1/linazhan/.bashrc

==> For changes to take effect, close and re-open your current shell. <==

/var/spool/slurm/d/job15270262/slurm_script: line 20: cuda: command not found
/var/spool/slurm/d/job15270262/slurm_script: line 21: nvidia-sm: command not found
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

ERROR: The control display is undefined; please run `nvidia-settings --help` for usage information.

[34m[1mval: [0myolo_model=yolo_nas_s.pt, reid_model=osnetx1_0_dukemtcereid.pt, tracking_method=deepocsort, name=exp, classes=['0'], project=/home1/linazhan/yolo_tracking/examples/runs/val, exist_ok=False, benchmark=MOT16, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
[32m2023-06-14 20:59:01.920[0m | [1mINFO    [0m | [36m__main__[0m:[36mdownload_mot_eval_tools[0m:[36m64[0m - [1mEval repo already downloaded[0m
[32m2023-06-14 20:59:01.926[0m | [1mINFO    [0m | [36m__main__[0m:[36meval[0m:[36m195[0m - [1mStaring evaluation process on /home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-11/MOT16-11[0m
[32m2023-06-14 20:59:38.169[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36meval[0m:[36m227[0m - [32m[1m/home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-11/MOT16-11 evaluation succeeded[0m
[32m2023-06-14 20:59:38.170[0m | [1mINFO    [0m | [36m__main__[0m:[36meval[0m:[36m195[0m - [1mStaring evaluation process on /home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-02/MOT16-02[0m
[32m2023-06-14 20:59:47.006[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36meval[0m:[36m227[0m - [32m[1m/home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-02/MOT16-02 evaluation succeeded[0m
[32m2023-06-14 20:59:47.008[0m | [1mINFO    [0m | [36m__main__[0m:[36meval[0m:[36m195[0m - [1mStaring evaluation process on /home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-05/MOT16-05[0m
[32m2023-06-14 20:59:55.228[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36meval[0m:[36m227[0m - [32m[1m/home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-05/MOT16-05 evaluation succeeded[0m
[32m2023-06-14 20:59:55.230[0m | [1mINFO    [0m | [36m__main__[0m:[36meval[0m:[36m195[0m - [1mStaring evaluation process on /home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-04/MOT16-04[0m
[32m2023-06-14 21:00:03.446[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36meval[0m:[36m227[0m - [32m[1m/home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-04/MOT16-04 evaluation succeeded[0m
[32m2023-06-14 21:00:03.449[0m | [1mINFO    [0m | [36m__main__[0m:[36meval[0m:[36m195[0m - [1mStaring evaluation process on /home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-09/MOT16-09[0m
[32m2023-06-14 21:00:12.006[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36meval[0m:[36m227[0m - [32m[1m/home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-09/MOT16-09 evaluation succeeded[0m
[32m2023-06-14 21:00:12.008[0m | [1mINFO    [0m | [36m__main__[0m:[36meval[0m:[36m195[0m - [1mStaring evaluation process on /home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-10/MOT16-10[0m
[32m2023-06-14 21:00:20.210[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36meval[0m:[36m227[0m - [32m[1m/home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-10/MOT16-10 evaluation succeeded[0m
[32m2023-06-14 21:00:20.213[0m | [1mINFO    [0m | [36m__main__[0m:[36meval[0m:[36m195[0m - [1mStaring evaluation process on /home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-13/MOT16-13[0m
[32m2023-06-14 21:00:28.507[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36meval[0m:[36m227[0m - [32m[1m/home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-13/MOT16-13 evaluation succeeded[0m
[34m[1mval: [0myolo_model=yolo_nas_s.pt, reid_model=osnetx1_0_dukemtcereid.pt, tracking_method=deepocsort, name=exp, classes=['0'], project=/home1/linazhan/yolo_tracking/examples/runs/val, exist_ok=False, benchmark=MOT16, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
[32m2023-06-14 21:00:29.969[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36meval[0m:[36m260[0m - [31m[1mTraceback (most recent call last):
  File "/home1/linazhan/yolo_tracking/examples/val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/home1/linazhan/yolo_tracking/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: labels//MOT16-11.txt
[0m
[32m2023-06-14 21:00:29.970[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36meval[0m:[36m261[0m - [31m[1m
Eval Config:
USE_PARALLEL         : True                          
NUM_PARALLEL_CORES   : 4                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /home1/linazhan/yolo_tracking/examples/val_utils/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train
TRACKERS_FOLDER      : /home1/linazhan/yolo_tracking/examples/runs/val/exp7
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['labels']                    
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            :                               
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   :                               
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : {'MOT16-11': None, 'MOT16-02': None, 'MOT16-05': None, 'MOT16-04': None, 'MOT16-09': None, 'MOT16-10': None, 'MOT16-13': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          
Tracker file not found: /home1/linazhan/yolo_tracking/examples/runs/val/exp7/labels/MOT16-11.txt
[0m

### Environment

1

### Minimal Reproducible Example

1

**Comment by mikel-brostrom** [comment]
> �[36m__main__�[0m:�[36meval�[0m:�[36m227�[0m - �[32m�[1m/home1/linazhan/yolo_tracking/examples/val_utils/data/MOT16/train/MOT16-11/MOT16-11 evaluation succeeded�[0m

It evaluated MOT16-11 successfully... Run again?

**Comment by Jumabek** [comment]
Facing the same error as @LinaZhangUSC 

System:
- Ubuntu2022.04
- venv

**Comment by Jumabek** [comment]
yes, in the second run, it worked)

**Comment by uopop** [comment]
I have also encountered such a problem. How did I solve it?

**Comment by yonadance** [comment]
run three times, still not solved

**Comment by 11jia** [comment]
D:\Anaconda\envs\yolov8\python.exe D:/yolo_tracking/tracking/val.py
2024-05-11 19:07:38.291 | INFO     | tracking.utils:download_mot_eval_tools:39 - Evaluation repo already downloaded or an error occurred: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/JonathonLuiten/TrackEval D:\yolo_tracking\tracking\val_utils
  stderr: 'fatal: destination path 'D:\yolo_tracking\tracking\val_utils' already exists and is not an empty directory.
'
'xargs' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2024-05-11 19:11:46.825 | ERROR    | tracking.utils:download_mot_eval_tools:55 - Error occurred while trying to replace np.float with float: Command 'grep -rl np.float D:\yolo_tracking\tracking\val_utils | xargs sed -i 's/np.float/float/g'' returned non-zero exit status 255.
'xargs' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2024-05-11 19:15:31.446 | ERROR    | tracking.utils:download_mot_eval_tools:55 - Error occurred while trying to replace np.int with int: Command 'grep -rl np.int D:\yolo_tracking\tracking\val_utils | xargs sed -i 's/np.int/int/g'' returned non-zero exit status 255.
'xargs' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2024-05-11 19:19:06.963 | ERROR    | tracking.utils:download_mot_eval_tools:55 - Error occurred while trying to replace np.bool with bool: Command 'grep -rl np.bool D:\yolo_tracking\tracking\val_utils | xargs sed -i 's/np.bool/bool/g'' returned non-zero exit status 255.
2024-05-11 19:19:06.964 | INFO     | tracking.utils:download_mot_dataset:102 - MOT17.zip already exists.
2024-05-11 19:19:06.964 | INFO     | tracking.utils:unzip_mot_dataset:134 - MOT17 folder already exists.
Standard Output:
 
Eval Config:
USE_PARALLEL         : True                          
NUM_PARALLEL_CORES   : 4                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : D:\yolo_tracking\tracking\val_utils\error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : D:\yolo_tracking\tracking\val_utils\data\MOT17\train
TRACKERS_FOLDER      : D:\yolo_tracking\runs\mot\yolov8n_osnet_x0_25_msmt17_deepocsort
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['']                          
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            :                               
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   :                               
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : {'MOT17-02-FRCNN': None, 'MOT17-04-FRCNN': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          
Tracker file not found: D:\yolo_tracking\runs\mot\yolov8n_osnet_x0_25_msmt17_deepocsort\MOT17-02-FRCNN.txt

Standard Error:
 Traceback (most recent call last):
  File "D:\yolo_tracking\tracking\val_utils\scripts\run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "D:\yolo_tracking\tracking\val_utils\trackeval\datasets\mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: //MOT17-02-FRCNN.txt

{}

进程已结束，退出代码 0
我也遇到了类似的问题，请问你们是怎么解决的？
